# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RentalInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


'''
 * @ author Joshua Jones
 * Created Date/Modified: jul, 2020
 * mail me at joshuajonesegbert@gmail.com in case of any query

 '''

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QBrush,QPalette,QImage
from PyQt5.QtCore import QSize
from PyQt5.QtWidgets import QMessageBox


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(502, 514)
        background_img = QImage("image2.jpg")
        scaled_img = background_img.scaled(QSize(553, 554))
        palette = QPalette()
        palette.setBrush(10, QBrush(scaled_img))
        Dialog.setPalette(palette)
        Dialog.setWindowIcon(QtGui.QIcon("icon1.jpg"))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 40, 411, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.days_label_2 = QtWidgets.QLabel(Dialog)
        self.days_label_2.setGeometry(QtCore.QRect(160, 130, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.days_label_2.setFont(font)
        self.days_label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.days_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.days_label_2.setObjectName("days_label_2")
        self.startReading_label_3 = QtWidgets.QLabel(Dialog)
        self.startReading_label_3.setGeometry(QtCore.QRect(150, 180, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.startReading_label_3.setFont(font)
        self.startReading_label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.startReading_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.startReading_label_3.setObjectName("startReading_label_3")
        self.endReading_label_4 = QtWidgets.QLabel(Dialog)
        self.endReading_label_4.setGeometry(QtCore.QRect(150, 230, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.endReading_label_4.setFont(font)
        self.endReading_label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.endReading_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.endReading_label_4.setObjectName("endReading_label_4")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(320, 130, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(320, 180, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(320, 230, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.clear_pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.clear_pushButton_2.setGeometry(QtCore.QRect(310, 300, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.clear_pushButton_2.setFont(font)
        self.clear_pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.clear_pushButton_2.setObjectName("clear_pushButton_2")
        self.fee_pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.fee_pushButton_3.setGeometry(QtCore.QRect(160, 300, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fee_pushButton_3.setFont(font)
        self.fee_pushButton_3.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.fee_pushButton_3.setObjectName("fee_pushButton_3")
        self.result_plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.result_plainTextEdit.setGeometry(QtCore.QRect(140, 380, 311, 131))
        self.result_plainTextEdit.setStyleSheet("border-color: rgb(255, 85, 0);")
        self.result_plainTextEdit.setObjectName("result_plainTextEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.fee_pushButton_3.clicked.connect(self.calculate_fee)
        self.clear_pushButton_2.clicked.connect(self.clear_all)

    def invalid_input(self):
        infoBox = QMessageBox()
        infoBox.setIcon(QMessageBox.Warning)
        infoBox.setText("Invalid Input")
        infoBox.setInformativeText("Invalid or Empty Input provided")
        infoBox.setWindowTitle("Warning")
        infoBox.exec_()

    def calculate_fee(self):
        days = self.lineEdit.text().strip()  # strip method here is to remov    e unwanted spaces if user has made
        startread = self.lineEdit_2.text().strip()
        endread= self.lineEdit_3.text().strip()

        if days == "" or startread == "" or endread == "":
            self.invalid_input()
        else:
            print (days, startread, endread)
            try:
                days = int(days)
                startread = float(startread)
                endread = float(endread)

                rental_fee = 0
                mileage_charge = 0

                driven_km = endread-startread
                dailycharge = days*60
                rental_fee += dailycharge
                avg_km = driven_km/days

                if avg_km > 80:
                    total_km = days*80
                    driven_above = driven_km-total_km
                    mileage_charge += (driven_above* 0.25)
                    rental_fee += mileage_charge


                output = "Daily Charge : ${} \n Mileage_charge : ${} \n Rental_fee : ${}".format(dailycharge,mileage_charge,
                                                                                                 rental_fee)
                self.result_plainTextEdit.setPlainText(output)
                # print(output)

            except Exception:
                self.invalid_input()


    def clear_all(self):
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Welcome to Online Vehicle Rental System"))
        self.days_label_2.setText(_translate("Dialog", "No of Days"))
        self.startReading_label_3.setText(_translate("Dialog", "Reading at Start"))
        self.endReading_label_4.setText(_translate("Dialog", "Reading at End "))
        self.clear_pushButton_2.setText(_translate("Dialog", "Clear"))
        self.fee_pushButton_3.setText(_translate("Dialog", "Calculate Fee"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
